name: lavacar
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  package_info_plus: ^1.4.3+1
  device_info_plus: ^4.1.2
  shared_preferences: ^2.0.15
  dio: ^4.0.0
  dotted_line: ^3.0.0
  page_transition: ^2.0.9
  auto_size_text: ^3.0.0
  month_picker_dialog_2: ^0.6.1+2
  timezone: ^0.9.0
  calendar_agenda: ^0.0.2+3
  crypto: ^3.0.1
  intl: ^0.17.0
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.1
  permission_handler: ^10.0.0
  rflutter_alert: ^2.0.4
  url_launcher: ^6.1.9
  loading_animation_widget: ^1.2.0+2
  flutter_facebook_auth: ^4.4.1+1
  google_sign_in: ^5.0.7
  firebase_auth: ^4.4.2
  firebase_messaging: ^14.4.1
  firebase_core: ^2.10.0
  badges: ^2.0.1
  flutter_local_notifications: ^13.0.0
  firebase_core_web: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: subtitle
      fonts:
        - asset: assets/fonts/subtitle.ttf
    - family: title
      fonts:
        - asset: assets/fonts/title.ttf

